version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    networks:
      global:
          ipv4_address: "172.16.1.100"
  redis:
    image: "redis:alpine"
    networks:
      global:

networks:
    global:
     external: true
