---
- hosts: my-ec2
  gather_facts: false
  tasks:
    - name: Tear down existing services
      docker_compose:
        project_name: counter
        definition:
          version: '2'
          services:
            web:
              build: "{{ playbook_dir }}/."
              ports:
                - "5000:5000"
            redis:
              image: "redis:alpine"
